name: sample
on:
  pull_request:
    types:
      - closed
    branches:
      - main

permissions:
  actions: read
  contents: read

env:
  SNOWFLAKE_ACCOUNT: ${{ secrets.SNOWFLAKE_ACCOUNT }}
  SNOWFLAKE_USER: ${{ secrets.SNOWFLAKE_USER }}
  SNOWFLAKE_PRIVATE_KEY: ${{ secrets.SNOWFLAKE_PRIVATE_KEY }}
  SNOWFLAKE_PRIVATE_KEY_PASSPHRASE: ${{ secrets.SNOWFLAKE_PRIVATE_KEY_PASSPHRASE }}
  SNOWFLAKE_DATABASE: ${{ secrets.SNOWFLAKE_DATABASE }}
  SNOWFLAKE_SCHEMA: ${{ secrets.SNOWFLAKE_SCHEMA }}
  SNOWFLAKE_WAREHOUSE: ${{ secrets.SNOWFLAKE_WAREHOUSE }}
  SNOWFLAKE_ROLE: ${{ secrets.SNOWFLAKE_ROLE }}

jobs:
  sample:
    if: github.event.pull_request.merged == true
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v6
      - name: dbt job
        uses: ta93abe/dbt-job@v1
        with:
          type: merge
          adapter: snowflake
          project-dir: hello
          profile-dir: hello
          command: |
            dbt seed --select state:modified+
            dbt run --select state:modified+
            dbt test --select state:modified+
          deferral: main
          target: prod
          run-timeout: 600
          dbt-version: 1.11
          threads: 8
