name: "dbt Run"
description: "Execute a dbt command with automatic profiles-dir and target injection"

inputs:
  command:
    description: "dbt command to execute (e.g. 'dbt build', 'dbt test --select tag:critical')"
    required: true
  project-dir:
    description: "Path to the dbt project root"
    required: false
    default: "."
  profiles-dir:
    description: "Directory containing profiles.yml"
    required: false
    default: "~/.dbt"
  target:
    description: "dbt target to use"
    required: false
    default: ""

outputs:
  result:
    description: "Command result: success or failure"
    value: ${{ steps.run.outputs.result }}
  log:
    description: "Path to the dbt log file"
    value: ${{ steps.run.outputs.log }}
  run-results:
    description: "Path to run_results.json if generated"
    value: ${{ steps.run.outputs.run-results }}
  manifest:
    description: "Path to manifest.json if generated"
    value: ${{ steps.run.outputs.manifest }}

runs:
  using: "composite"
  steps:
    - name: Run dbt command
      id: run
      shell: bash
      working-directory: ${{ inputs.project-dir }}
      env:
        DBT_CMD: ${{ inputs.command }}
        DBT_PROFILES_DIR: ${{ inputs.profiles-dir }}
        DBT_TARGET: ${{ inputs.target }}
        DBT_PROJECT_DIR: ${{ inputs.project-dir }}
      run: |
        profiles_dir="$DBT_PROFILES_DIR"
        profiles_dir="${profiles_dir/#\~/$HOME}"

        if CMD="$DBT_CMD" DBT_PROFILES_DIR="$profiles_dir" python3 - <<'PY'
        import os
        import shlex
        import subprocess
        import sys

        ALLOWED = frozenset({
            "build", "run", "test", "seed", "snapshot",
            "compile", "parse", "deps", "ls", "list",
            "source", "freshness", "show", "retry", "clone",
        })

        cmd = os.environ.get("CMD", "")
        profiles_dir = os.environ.get("DBT_PROFILES_DIR", "")
        target = os.environ.get("DBT_TARGET", "")

        try:
            args = shlex.split(cmd, posix=True)
        except ValueError as exc:
            print(f"::error::Invalid command syntax: {exc}")
            sys.exit(2)

        if not args or args[0] != "dbt":
            print("::error::Only dbt commands are allowed.")
            sys.exit(2)

        subcmd = next((a for a in args[1:] if not a.startswith("-")), None)
        if subcmd is None or subcmd not in ALLOWED:
            print(f"::error::Subcommand not allowed: {subcmd or '(none)'}")
            sys.exit(2)

        if profiles_dir and "--profiles-dir" not in args:
            args += ["--profiles-dir", profiles_dir]
        if target and "--target" not in args:
            args += ["--target", target]

        print(f"Running: {' '.join(shlex.quote(a) for a in args)}")
        completed = subprocess.run(args, check=False)
        sys.exit(completed.returncode)
        PY
        then
          echo "result=success" >> "$GITHUB_OUTPUT"
        else
          echo "result=failure" >> "$GITHUB_OUTPUT"
          exit 1
        fi

        # Export artifact paths
        target_dir="${DBT_PROJECT_DIR}/target"
        if [[ -f "$target_dir/run_results.json" ]]; then
          echo "run-results=$target_dir/run_results.json" >> "$GITHUB_OUTPUT"
        fi
        if [[ -f "$target_dir/manifest.json" ]]; then
          echo "manifest=$target_dir/manifest.json" >> "$GITHUB_OUTPUT"
        fi
        if [[ -d "$target_dir" ]]; then
          echo "log=$target_dir/dbt.log" >> "$GITHUB_OUTPUT"
        fi
