name: "dbt Setup"
description: "Set up Python, dbt-core, and a dbt adapter with uv"

inputs:
  adapter:
    description: "dbt adapter short name (e.g. snowflake)"
    required: true
  dbt-version:
    description: "Explicit dbt-core version. If empty, resolved from pyproject.toml or latest."
    required: false
    default: ""
  profiles-yml:
    description: "Contents of profiles.yml to write"
    required: false
    default: ""
  profiles-dir:
    description: "Directory to write profiles.yml into"
    required: false
    default: "~/.dbt"
  project-dir:
    description: "Path to the dbt project root"
    required: false
    default: "."

outputs:
  dbt-version:
    description: "Installed dbt-core version"
    value: ${{ steps.install.outputs.dbt-version }}

runs:
  using: "composite"
  steps:
    - name: Validate and normalize adapter
      id: normalize-adapter
      shell: bash
      env:
        INPUT_ADAPTER: ${{ inputs.adapter }}
      run: |
        adapter="$INPUT_ADAPTER"
        adapter="${adapter#dbt-}"
        adapter="${adapter,,}"

        case "$adapter" in
          snowflake)
            echo "adapter_package=dbt-snowflake" >> "$GITHUB_OUTPUT"
            ;;
          *)
            echo "::error::Unsupported adapter: ${INPUT_ADAPTER}. Supported adapters: snowflake"
            exit 1
            ;;
        esac

    - name: Install uv
      uses: astral-sh/setup-uv@v7

    - name: Resolve dbt version
      id: resolve
      shell: bash
      env:
        ACTION_PATH: ${{ github.action_path }}
        DBT_VERSION_INPUT: ${{ inputs.dbt-version }}
        DBT_PROJECT_DIR: ${{ inputs.project-dir }}
      run: |
        version=$("${ACTION_PATH}/../../scripts/resolve-version.sh" \
          "$DBT_VERSION_INPUT" \
          "$DBT_PROJECT_DIR")
        echo "version=$version" >> "$GITHUB_OUTPUT"

    - name: Install dbt
      id: install
      shell: bash
      env:
        DBT_VERSION: ${{ steps.resolve.outputs.version }}
        DBT_ADAPTER_PACKAGE: ${{ steps.normalize-adapter.outputs.adapter_package }}
      run: |
        if [[ -n "$DBT_VERSION" ]]; then
          uv pip install --system "dbt-core==${DBT_VERSION}" "${DBT_ADAPTER_PACKAGE}"
        else
          uv pip install --system dbt-core "${DBT_ADAPTER_PACKAGE}"
        fi

        installed_version=$(dbt --version | grep -oP 'installed: \K[0-9]+\.[0-9]+\.[0-9]+' | head -1 || dbt --version | grep -oE '[0-9]+\.[0-9]+\.[0-9]+' | head -1)
        echo "dbt-version=${installed_version}" >> "$GITHUB_OUTPUT"

    - name: Write profiles.yml
      if: inputs.profiles-yml != ''
      shell: bash
      env:
        PROFILES_YML: ${{ inputs.profiles-yml }}
        PROFILES_DIR: ${{ inputs.profiles-dir }}
      run: |
        profiles_dir="$PROFILES_DIR"
        profiles_dir="${profiles_dir/#\~/$HOME}"
        mkdir -p "$profiles_dir"
        printf '%s\n' "$PROFILES_YML" > "$profiles_dir/profiles.yml"
